# include:
#   - compose.observability.yaml
services:
  speaches:
    extends:
      file: compose.speaches.yaml
      service: speaches
    image: ghcr.io/speaches-ai/speaches:latest-cpu
    build:
      args:
        BASE_IMAGE: ubuntu:24.04
    volumes:
      - ${HF_HUB_CACHE}:/home/ubuntu/.cache/huggingface/hub
networks:
  speaches-network:
    external: false
